tasks:
  - name: Import vars
    include_vars:
      file: ./version.yml
      name: vardata

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejsapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejsapp
  template:
    metadata:
      labels:
        app: nodejsapp
    spec:
      # imagePullSecrets:
      # - name: aws-ecr-secret
      containers:
      - name: nodejsapp-latest
        image: my-image:87
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000


